language: python

sudo: false

python:
  - "2.7"
  - "3.6"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip atlas numpy=1.11.2 scipy=0.18.1 hdf4 libnetcdf netcdf4=1.2.4 pytest
  - source activate test-environment
  - pip install -r requirements_dev.txt
  - pip install codecov pytest-cov
  - python setup.py install

before_script:
  # Download the required climatology files.
  - python -c "import oceansdb; oceansdb.WOA()['sea_water_temperature']"
  - python -c "import oceansdb; oceansdb.CARS()['sea_water_temperature']"
  - python -c "import oceansdb; oceansdb.ETOPO()['topography']"

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
